verbose: false
instrumentation:
  root: './app/'
  excludes:
    - '*test.*'
  extensions:
    - .js
    - .jsx
  es-modules: true
  include-all-sources: true
reporting:
  reports:
    watermarks:
      statements: [80, 100]
      lines: [80, 100]
      branches: [80, 100]
      functions: [80, 100]
check:
  global:
    statements: 100
    lines: 100
    branches: 100
    functions: 100
