# inherit_from: rubocop_todo.yml

Rails:
  Enabled: true

AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'config/application.rb'
    - 'config/environments/**/*'
    - 'config/initializers/**/*'
    - 'test/test_helper.rb'
    - 'test/teaspoon_env.rb'
    - 'test/support/**/*'
    - 'client/node_modules/**/*'

HasAndBelongsToMany:
  Enabled: false

Documentation:
  Enabled: false

MethodDefParentheses:
  Enabled: false

GuardClause:
  Enabled: false

RedundantSelf:
  Enabled: false

LineLength:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

# Metrics/MethodLength:
#   Max: 1

# Metrics/AbcSize:
#   Max: 1
