translations:
  - file: "client/vendor/translations.js"
    only: ["*.layouts.*", "*.pages.*", "*.LoggedIn.*", "*.PledgeForm.*",
      "*.PledgeFormHelp.*", "*.PledgeQuote.*", "*.PledgeFeatures.*",
      "*.ImageInputComponent.*", "*.ImageCrop.*", "*.PledgeUpdateList.*",
      "*.PledgeCommentList.*", "*.PledgeImage.*", "*.SigneeList.*",
      "*.Signee.*", "*.SignInForm.*", "*.Session.*", "*.PledgeSignedMessage.*",
      "*.PaginatedSearchResults.*", "*.PledgeCreatedAt.*",
      "*.ProfileUserForm.*", "*.ReportPledgeForm.*", "*.SignPledgeForm.*",
      "*.FacebookButton.*", "*.TwitterButton.*", "*.GoogleplusButton.*",
      "*.LinkedinButton.*", "*.XingButton.*", "*.StateHeader.*",
      "*.StateFooter.*", "*.PledgeData.*", "*.UpdateForm.*", "*.AnswerForm.*",
      "*.QuestionForm.*", "*.PledgeState.*", "*.ProfileView.*",
      "*.CommentAvatar.*", "*.PledgeLocation.*", "*.PledgeTileBack.*",
      "*.PledgeTileFront.*", "*.PreviewExplanation.*", "*.PreviewDraft.*",
      "*.PreviewUnconfirmed.*", "*.PreviewRequested.*",
      "*.rform.*", "*.paths.*", "*.tags.*"]
